[www]

listen = 127.0.0.1:9000

user = www-data
group = www-data

pm = dynamic
pm.max_children = 50
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
pm.max_requests = 5000

pm.status_path = /phpstatus

ping.path = /phpping
ping.response = pong

php_admin_value[disable_functions] = shell_exec