services:

  php:
    container_name: php
    build:
      context: .
      dockerfile: Docker/php-8.2/Dockerfile
      target: php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 9000:8080
    depends_on:
      - database
    networks:
      - lemp

  database:
    container_name: database
    image: mysql:8.2
    ports:
      - 33061:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - lemp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80" 
    networks:
      - lemp

volumes:
  db-data: ~

networks:
  lemp:
    driver: bridge